# version: '3.8'

services:
  db:
    image: postgres:15
    container_name: yalp_postgres
    environment:
      POSTGRES_USER: yalp_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: yalp
    ports:
      - "7070:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: yalp_app
    env_file:
      - .env  # Load the .env file
    depends_on:
      - db
    ports:
      - "9090:9090"
    restart: on-failure
    entrypoint: ["sh", "-c", "until pg_isready -h db -p 5432; do echo waiting for db; sleep 2; done; ./main"]

volumes:
  postgres_data:
